# Permalinks
permalink:           pretty

# Setup
title:               Personal Portfolio
tagline:             Fork me and create your own.
url:                 https://refugees-code.github.io/portfolio/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Dario Seidl
  url:               https://github.com/darioseidl
  email:

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/Refugees-Code/portfolio
google_analytics:
twitter:
github:              refugees-code
dribbble:

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

theme: jekyll-theme-slate